// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelOrganiserTool.Data;

#nullable disable

namespace TravelOrganiserTool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240130053757_initialCreate8")]
    partial class initialCreate8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionID");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Australia",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Burma",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cambodia",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "China",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "India",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Indonesia",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Japan",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "North Korea",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Malaysia",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Singapore",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "South Korea",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "Thailand",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "The Philippines",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Vietnam",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Germany",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "France",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 17,
                            Name = "USA",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 18,
                            Name = "Canada",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 19,
                            Name = "Brazil",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 20,
                            Name = "Argentina",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 21,
                            Name = "South Africa",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 22,
                            Name = "Kenya",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 23,
                            Name = "Antarctica",
                            RegionID = 7
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryID");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryID = 1,
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = 2,
                            CountryID = 2,
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = 3,
                            CountryID = 3,
                            Name = "Seoul"
                        },
                        new
                        {
                            Id = 4,
                            CountryID = 4,
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 5,
                            CountryID = 5,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 6,
                            CountryID = 6,
                            Name = "New York"
                        },
                        new
                        {
                            Id = 7,
                            CountryID = 7,
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = 8,
                            CountryID = 8,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 9,
                            CountryID = 9,
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = 10,
                            CountryID = 10,
                            Name = "Johannesburg"
                        },
                        new
                        {
                            Id = 11,
                            CountryID = 11,
                            Name = "Nairobi"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Region");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Asia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Europe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "North America"
                        },
                        new
                        {
                            Id = 5,
                            Name = "South America"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Africa"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Antarctica"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationID");

                    b.ToTable("Trip");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocationID = 1,
                            Name = "Example Trip: Visiting Family in Sydney"
                        },
                        new
                        {
                            Id = 2,
                            LocationID = 2,
                            Name = "Example Trip: Visiting Tokyo"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.Region", "Region")
                        .WithMany("Countries")
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Location", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.Country", "Country")
                        .WithMany("Locations")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Trip", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.Location", "Location")
                        .WithMany("Trips")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Location", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Region", b =>
                {
                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
