// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelOrganiserTool.Data;

#nullable disable

namespace TravelOrganiserTool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240609131808_initialCreateAzure1")]
    partial class initialCreateAzure1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelOrganiserTool.Models.ClimateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClimateType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sunny"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tropical"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chilly"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Snowy"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageFilename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionID");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageFilename = "australia.jpg",
                            Name = "Australia",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageFilename = "malaysia.jpg",
                            Name = "Malaysia",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageFilename = "philippines.jpg",
                            Name = "Philippines",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 4,
                            ImageFilename = "singapore.jpg",
                            Name = "Singapore",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 5,
                            ImageFilename = "thailand.jpg",
                            Name = "Thailand",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageFilename = "vietnam.jpg",
                            Name = "Vietnam",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageFilename = "china.jpg",
                            Name = "China",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 8,
                            ImageFilename = "japan.jpg",
                            Name = "Japan",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 9,
                            ImageFilename = "south-korea.jpg",
                            Name = "South Korea",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageFilename = "india.jpg",
                            Name = "India",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 11,
                            ImageFilename = "no-image.jpg",
                            Name = "Kuwait",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 12,
                            ImageFilename = "no-image.jpg",
                            Name = "United Arab Emirates",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 13,
                            ImageFilename = "denmark.jpg",
                            Name = "Denmark",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 14,
                            ImageFilename = "finland.jpg",
                            Name = "Finland",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 15,
                            ImageFilename = "norway.jpg",
                            Name = "Norway",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 16,
                            ImageFilename = "united-kingdom.jpg",
                            Name = "United Kingdom",
                            RegionID = 7
                        },
                        new
                        {
                            Id = 17,
                            ImageFilename = "ireland.jpg",
                            Name = "Ireland",
                            RegionID = 7
                        },
                        new
                        {
                            Id = 18,
                            ImageFilename = "no-image.jpg",
                            Name = "Belgium",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 19,
                            ImageFilename = "france.jpg",
                            Name = "France",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 20,
                            ImageFilename = "germany.jpg",
                            Name = "Germany",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 21,
                            ImageFilename = "italy.jpg",
                            Name = "Italy",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 22,
                            ImageFilename = "no-image.jpg",
                            Name = "Russia",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 23,
                            ImageFilename = "no-image.jpg",
                            Name = "Sudan",
                            RegionID = 10
                        },
                        new
                        {
                            Id = 24,
                            ImageFilename = "kenya.jpg",
                            Name = "Kenya",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 25,
                            ImageFilename = "rwanda.jpg",
                            Name = "Rwanda",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 26,
                            ImageFilename = "south-africa.jpg",
                            Name = "South Africa",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 27,
                            ImageFilename = "canada.jpg",
                            Name = "Canada",
                            RegionID = 12
                        },
                        new
                        {
                            Id = 28,
                            ImageFilename = "mexico.jpg",
                            Name = "Mexico",
                            RegionID = 12
                        },
                        new
                        {
                            Id = 29,
                            ImageFilename = "united-states.jpg",
                            Name = "United States",
                            RegionID = 12
                        },
                        new
                        {
                            Id = 30,
                            ImageFilename = "no-image.jpg",
                            Name = "Costa Rica",
                            RegionID = 13
                        },
                        new
                        {
                            Id = 31,
                            ImageFilename = "jamaica.jpg",
                            Name = "Jamaica",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 32,
                            ImageFilename = "brazil.jpg",
                            Name = "Brazil",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 33,
                            ImageFilename = "chile.jpg",
                            Name = "Chile",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 34,
                            ImageFilename = "ecuador.jpg",
                            Name = "Ecuador",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 35,
                            ImageFilename = "peru.jpg",
                            Name = "Peru",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 36,
                            ImageFilename = "no-image.jpg",
                            Name = "Antarctica",
                            RegionID = 16
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClimateTypeID")
                        .HasColumnType("int");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("ImageFilename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PopulationTypeID")
                        .HasColumnType("int");

                    b.Property<int>("TerrainTypeID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClimateTypeID");

                    b.HasIndex("CountryID");

                    b.HasIndex("PopulationTypeID");

                    b.HasIndex("TerrainTypeID");

                    b.ToTable("Destination");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "adelaide.jpg",
                            Name = "Adelaide",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 2,
                            ClimateTypeID = 2,
                            CountryID = 1,
                            ImageFilename = "brisbane.jpg",
                            Name = "Brisbane",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 3,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "canberra.jpg",
                            Name = "Canberra",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 4,
                            ClimateTypeID = 3,
                            CountryID = 1,
                            ImageFilename = "hobart.jpg",
                            Name = "Hobart",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 5,
                            ClimateTypeID = 3,
                            CountryID = 1,
                            ImageFilename = "melbourne.jpg",
                            Name = "Melbourne",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 6,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "sydney.jpg",
                            Name = "Sydney",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 7,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "perth.jpg",
                            Name = "Perth",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 8,
                            ClimateTypeID = 2,
                            CountryID = 2,
                            ImageFilename = "kuala-lumpur.jpg",
                            Name = "Kuala Lumpur",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 9,
                            ClimateTypeID = 2,
                            CountryID = 3,
                            ImageFilename = "manila.jpg",
                            Name = "Manila",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 10,
                            ClimateTypeID = 2,
                            CountryID = 4,
                            ImageFilename = "singapore.jpg",
                            Name = "Singapore",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 11,
                            ClimateTypeID = 2,
                            CountryID = 5,
                            ImageFilename = "bangkok.jpg",
                            Name = "Bangkok",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 12,
                            ClimateTypeID = 2,
                            CountryID = 5,
                            ImageFilename = "phuket.jpg",
                            Name = "Phuket",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 13,
                            ClimateTypeID = 2,
                            CountryID = 6,
                            ImageFilename = "ho-chi-minh-city.jpg",
                            Name = "Ho Chi Minh City",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 14,
                            ClimateTypeID = 2,
                            CountryID = 6,
                            ImageFilename = "hanoi.jpg",
                            Name = "Hanoi",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 15,
                            ClimateTypeID = 1,
                            CountryID = 7,
                            ImageFilename = "beijing.jpg",
                            Name = "Beijing",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 16,
                            ClimateTypeID = 1,
                            CountryID = 7,
                            ImageFilename = "shanghai.jpg",
                            Name = "Shanghai",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 17,
                            ClimateTypeID = 3,
                            CountryID = 8,
                            ImageFilename = "tokyo.jpg",
                            Name = "Tokyo",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 18,
                            ClimateTypeID = 3,
                            CountryID = 8,
                            ImageFilename = "osaka.jpg",
                            Name = "Osaka",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 19,
                            ClimateTypeID = 3,
                            CountryID = 8,
                            ImageFilename = "hiroshima.jpg",
                            Name = "Hiroshima",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 20,
                            ClimateTypeID = 3,
                            CountryID = 9,
                            ImageFilename = "seoul.jpg",
                            Name = "Seoul",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 21,
                            ClimateTypeID = 1,
                            CountryID = 10,
                            ImageFilename = "mumbai.jpg",
                            Name = "Mumbai",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 22,
                            ClimateTypeID = 1,
                            CountryID = 10,
                            ImageFilename = "kolkata.jpg",
                            Name = "Kolkata",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 23,
                            ClimateTypeID = 1,
                            CountryID = 10,
                            ImageFilename = "hyderabad.jpg",
                            Name = "Hyderabad",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 24,
                            ClimateTypeID = 1,
                            CountryID = 11,
                            ImageFilename = "no-image.jpg",
                            Name = "Kuwait City",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 25,
                            ClimateTypeID = 1,
                            CountryID = 12,
                            ImageFilename = "no-image.jpg",
                            Name = "Dubai",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 26,
                            ClimateTypeID = 3,
                            CountryID = 13,
                            ImageFilename = "copenhagen.jpg",
                            Name = "Copenhagen",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 27,
                            ClimateTypeID = 3,
                            CountryID = 14,
                            ImageFilename = "helsinki.jpg",
                            Name = "Helsinki",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 28,
                            ClimateTypeID = 3,
                            CountryID = 15,
                            ImageFilename = "oslo.jpg",
                            Name = "Oslo",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 29,
                            ClimateTypeID = 1,
                            CountryID = 16,
                            ImageFilename = "london.jpg",
                            Name = "London",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 30,
                            ClimateTypeID = 1,
                            CountryID = 16,
                            ImageFilename = "bristol.jpg",
                            Name = "Bristol",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 31,
                            ClimateTypeID = 1,
                            CountryID = 16,
                            ImageFilename = "manchester.jpg",
                            Name = "Manchester",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 32,
                            ClimateTypeID = 1,
                            CountryID = 16,
                            ImageFilename = "birmingham.jpg",
                            Name = "Birmingham",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 33,
                            ClimateTypeID = 3,
                            CountryID = 17,
                            ImageFilename = "dublin.jpg",
                            Name = "Dublin",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 34,
                            ClimateTypeID = 3,
                            CountryID = 17,
                            ImageFilename = "galway.jpg",
                            Name = "Galway",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 35,
                            ClimateTypeID = 3,
                            CountryID = 18,
                            ImageFilename = "no-image.jpg",
                            Name = "Bruges",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 36,
                            ClimateTypeID = 3,
                            CountryID = 19,
                            ImageFilename = "paris.jpg",
                            Name = "Paris",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 37,
                            ClimateTypeID = 3,
                            CountryID = 20,
                            ImageFilename = "berlin.jpg",
                            Name = "Berlin",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 38,
                            ClimateTypeID = 1,
                            CountryID = 21,
                            ImageFilename = "rome.jpg",
                            Name = "Rome",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 39,
                            ClimateTypeID = 1,
                            CountryID = 21,
                            ImageFilename = "venice.jpg",
                            Name = "Venice",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 40,
                            ClimateTypeID = 1,
                            CountryID = 21,
                            ImageFilename = "florence.jpg",
                            Name = "Florence",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 41,
                            ClimateTypeID = 3,
                            CountryID = 22,
                            ImageFilename = "no-image.jpg",
                            Name = "Moscow",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 42,
                            ClimateTypeID = 1,
                            CountryID = 23,
                            ImageFilename = "no-image.jpg",
                            Name = "Kassala",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 43,
                            ClimateTypeID = 1,
                            CountryID = 24,
                            ImageFilename = "nairobi.jpg",
                            Name = "Nairobi",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 44,
                            ClimateTypeID = 1,
                            CountryID = 25,
                            ImageFilename = "kigali.jpg",
                            Name = "Kigali",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 45,
                            ClimateTypeID = 1,
                            CountryID = 26,
                            ImageFilename = "johannesburg.jpg",
                            Name = "Johannesburg",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 46,
                            ClimateTypeID = 3,
                            CountryID = 27,
                            ImageFilename = "toronto.jpg",
                            Name = "Toronto",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 47,
                            ClimateTypeID = 3,
                            CountryID = 27,
                            ImageFilename = "vancouver.jpg",
                            Name = "Vancouver",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 48,
                            ClimateTypeID = 1,
                            CountryID = 28,
                            ImageFilename = "mexico-city.jpg",
                            Name = "Mexico City",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 49,
                            ClimateTypeID = 3,
                            CountryID = 29,
                            ImageFilename = "boston.jpg",
                            Name = "Boston",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 50,
                            ClimateTypeID = 3,
                            CountryID = 29,
                            ImageFilename = "chicago.jpg",
                            Name = "Chicago",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 51,
                            ClimateTypeID = 1,
                            CountryID = 29,
                            ImageFilename = "los-angeles.jpg",
                            Name = "Los Angeles",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 52,
                            ClimateTypeID = 3,
                            CountryID = 29,
                            ImageFilename = "new-york.jpg",
                            Name = "New York",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 53,
                            ClimateTypeID = 2,
                            CountryID = 30,
                            ImageFilename = "no-image.jpg",
                            Name = "San Jose",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 54,
                            ClimateTypeID = 1,
                            CountryID = 31,
                            ImageFilename = "montego-bay.jpg",
                            Name = "Montego Bay",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 55,
                            ClimateTypeID = 1,
                            CountryID = 32,
                            ImageFilename = "rio-de-janeiro.jpg",
                            Name = "Rio de Janeiro",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 56,
                            ClimateTypeID = 1,
                            CountryID = 32,
                            ImageFilename = "salvador.jpg",
                            Name = "Salvador",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 57,
                            ClimateTypeID = 1,
                            CountryID = 32,
                            ImageFilename = "sao-paulo.jpg",
                            Name = "Sao Paulo",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 58,
                            ClimateTypeID = 3,
                            CountryID = 33,
                            ImageFilename = "santiago.jpg",
                            Name = "Santiago",
                            PopulationTypeID = 3,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 59,
                            ClimateTypeID = 3,
                            CountryID = 34,
                            ImageFilename = "quito.jpg",
                            Name = "Quito",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 60,
                            ClimateTypeID = 3,
                            CountryID = 35,
                            ImageFilename = "arequipa.jpg",
                            Name = "Arequipa",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 61,
                            ClimateTypeID = 4,
                            CountryID = 36,
                            ImageFilename = "mcmurdo-station.jpg",
                            Name = "McMurdo Station",
                            PopulationTypeID = 1,
                            TerrainTypeID = 11
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.PopulationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PopulationType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "City"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Town"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rural (Non Urban)"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Region");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oceania"
                        },
                        new
                        {
                            Id = 2,
                            Name = "South East Asia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "East Asia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "South Asia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Middle East"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Scandinavia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "United Kingdom and Western Europe"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Central Europe"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Southern Europe"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Eastern Europe and Former USSR"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Northern Africa"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Subsaharan Africa"
                        },
                        new
                        {
                            Id = 12,
                            Name = "North America"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Central America"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Caribbean"
                        },
                        new
                        {
                            Id = 15,
                            Name = "South America"
                        },
                        new
                        {
                            Id = 16,
                            Name = "South Pole"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.TerrainType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TerrainType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Major City"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Desert"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Forest"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cliffs"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hills"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Marsh"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Farmland"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Beach"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Coastal"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Waterfront"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Mountains"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trip");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Example Trip: Visiting Family in Sydney"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Example Trip: Visiting Tokyo"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Tripstop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Enddate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Startdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationID");

                    b.HasIndex("TripID");

                    b.ToTable("Tripstop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DestinationID = 1,
                            Enddate = new DateTime(2024, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Startdate = new DateTime(2024, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            TripID = 1
                        },
                        new
                        {
                            Id = 2,
                            DestinationID = 2,
                            Enddate = new DateTime(2024, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Startdate = new DateTime(2024, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            TripID = 1
                        },
                        new
                        {
                            Id = 3,
                            DestinationID = 3,
                            Enddate = new DateTime(2024, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Startdate = new DateTime(2024, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            TripID = 2
                        },
                        new
                        {
                            Id = 4,
                            DestinationID = 4,
                            Enddate = new DateTime(2024, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Startdate = new DateTime(2024, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            TripID = 2
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.Region", "Region")
                        .WithMany("Countries")
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Destination", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.ClimateType", "ClimateType")
                        .WithMany("Destinations")
                        .HasForeignKey("ClimateTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelOrganiserTool.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelOrganiserTool.Models.PopulationType", "PopulationType")
                        .WithMany("Destinations")
                        .HasForeignKey("PopulationTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelOrganiserTool.Models.TerrainType", "TerrainType")
                        .WithMany("Destinations")
                        .HasForeignKey("TerrainTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClimateType");

                    b.Navigation("Country");

                    b.Navigation("PopulationType");

                    b.Navigation("TerrainType");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Tripstop", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.Destination", "Destination")
                        .WithMany("Tripstops")
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelOrganiserTool.Models.Trip", "Trip")
                        .WithMany("Tripstops")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.ClimateType", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Destination", b =>
                {
                    b.Navigation("Tripstops");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.PopulationType", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Region", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.TerrainType", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Trip", b =>
                {
                    b.Navigation("Tripstops");
                });
#pragma warning restore 612, 618
        }
    }
}
