// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelOrganiserTool.Data;

#nullable disable

namespace TravelOrganiserTool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240515065046_initialCreate1")]
    partial class initialCreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageFilename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionID");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageFilename = "australia.jpg",
                            Name = "Australia",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageFilename = "no-image.jpg",
                            Name = "New Zealand",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageFilename = "no-image.jpg",
                            Name = "Solomon Islands",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageFilename = "no-image.jpg",
                            Name = "Cook Islands",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageFilename = "no-image.jpg",
                            Name = "Papua New Guinea",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 6,
                            ImageFilename = "no-image.jpg",
                            Name = "Fiji",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 7,
                            ImageFilename = "no-image.jpg",
                            Name = "Micronesia",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 8,
                            ImageFilename = "no-image.jpg",
                            Name = "Samoa",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 9,
                            ImageFilename = "no-image.jpg",
                            Name = "Vanuatu",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 10,
                            ImageFilename = "no-image.jpg",
                            Name = "Brunei",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 11,
                            ImageFilename = "no-image.jpg",
                            Name = "Burma",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 12,
                            ImageFilename = "no-image.jpg",
                            Name = "Cambodia",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 13,
                            ImageFilename = "no-image.jpg",
                            Name = "Timor-Leste",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 14,
                            ImageFilename = "no-image.jpg",
                            Name = "Indonesia",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 15,
                            ImageFilename = "no-image.jpg",
                            Name = "Laos",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 16,
                            ImageFilename = "malaysia.jpg",
                            Name = "Malaysia",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 17,
                            ImageFilename = "philippines.jpg",
                            Name = "Philippines",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 18,
                            ImageFilename = "singapore.jpg",
                            Name = "Singapore",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 19,
                            ImageFilename = "thailand.jpg",
                            Name = "Thailand",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 20,
                            ImageFilename = "vietnam.jpg",
                            Name = "Vietnam",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 21,
                            ImageFilename = "china.jpg",
                            Name = "China",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 22,
                            ImageFilename = "japan.jpg",
                            Name = "Japan",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 23,
                            ImageFilename = "no-image.jpg",
                            Name = "Mongolia",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 24,
                            ImageFilename = "south-korea.jpg",
                            Name = "South Korea",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 25,
                            ImageFilename = "no-image.jpg",
                            Name = "North Korea",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 26,
                            ImageFilename = "no-image.jpg",
                            Name = "Taiwan",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 27,
                            ImageFilename = "no-image.jpg",
                            Name = "Macao",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 28,
                            ImageFilename = "no-image.jpg",
                            Name = "Hong Kong",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 29,
                            ImageFilename = "no-image.jpg",
                            Name = "Afghanistan",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 30,
                            ImageFilename = "no-image.jpg",
                            Name = "Bangladesh",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 31,
                            ImageFilename = "no-image.jpg",
                            Name = "Bhutan",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 32,
                            ImageFilename = "india.jpg",
                            Name = "India",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 33,
                            ImageFilename = "no-image.jpg",
                            Name = "Nepal",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 34,
                            ImageFilename = "no-image.jpg",
                            Name = "Maldives",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 35,
                            ImageFilename = "no-image.jpg",
                            Name = "Pakistan",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 36,
                            ImageFilename = "no-image.jpg",
                            Name = "Sri Lanka",
                            RegionID = 4
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("ImageFilename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryID");

                    b.ToTable("Destination");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryID = 1,
                            ImageFilename = "adelaide.jpg",
                            Name = "Adelaide"
                        },
                        new
                        {
                            Id = 2,
                            CountryID = 1,
                            ImageFilename = "brisbane.jpg",
                            Name = "Brisbane"
                        },
                        new
                        {
                            Id = 3,
                            CountryID = 1,
                            ImageFilename = "canberra.jpg",
                            Name = "Canberra"
                        },
                        new
                        {
                            Id = 4,
                            CountryID = 1,
                            ImageFilename = "hobart.jpg",
                            Name = "Hobart"
                        },
                        new
                        {
                            Id = 5,
                            CountryID = 1,
                            ImageFilename = "melbourne.jpg",
                            Name = "Melbourne"
                        },
                        new
                        {
                            Id = 6,
                            CountryID = 1,
                            ImageFilename = "sydney.jpg",
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = 7,
                            CountryID = 1,
                            ImageFilename = "perth.jpg",
                            Name = "Perth"
                        },
                        new
                        {
                            Id = 8,
                            CountryID = 1,
                            ImageFilename = "no-image.jpg",
                            Name = "Newcastle"
                        },
                        new
                        {
                            Id = 9,
                            CountryID = 1,
                            ImageFilename = "no-image.jpg",
                            Name = "Central Coast"
                        },
                        new
                        {
                            Id = 10,
                            CountryID = 1,
                            ImageFilename = "no-image.jpg",
                            Name = "Hunter Valley"
                        },
                        new
                        {
                            Id = 11,
                            CountryID = 1,
                            ImageFilename = "no-image.jpg",
                            Name = "Nelson Bay"
                        },
                        new
                        {
                            Id = 12,
                            CountryID = 1,
                            ImageFilename = "no-image.jpg",
                            Name = "Port Macquarie"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Region");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oceania"
                        },
                        new
                        {
                            Id = 2,
                            Name = "South East Asia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "East Asia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "South Asia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Middle East"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Scandinavia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Western Europe"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Southern Europe"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Northern Africa"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Subsaharan Africa"
                        },
                        new
                        {
                            Id = 12,
                            Name = "North America"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Central America"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Caribbean"
                        },
                        new
                        {
                            Id = 15,
                            Name = "South America"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Polar Regions"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trip");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Example Trip: Visiting Family in Sydney"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Example Trip: Visiting Tokyo"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Tripstop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Enddate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Startdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationID");

                    b.HasIndex("TripID");

                    b.ToTable("Tripstop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DestinationID = 1,
                            Enddate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Startdate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            TripID = 1
                        },
                        new
                        {
                            Id = 2,
                            DestinationID = 2,
                            Enddate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Startdate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            TripID = 1
                        },
                        new
                        {
                            Id = 3,
                            DestinationID = 3,
                            Enddate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Startdate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            TripID = 2
                        },
                        new
                        {
                            Id = 4,
                            DestinationID = 4,
                            Enddate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            Startdate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            TripID = 2
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.Region", "Region")
                        .WithMany("Countries")
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Destination", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Tripstop", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.Destination", "Destination")
                        .WithMany("Tripstops")
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelOrganiserTool.Models.Trip", "Trip")
                        .WithMany("Tripstops")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Destination", b =>
                {
                    b.Navigation("Tripstops");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Region", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Trip", b =>
                {
                    b.Navigation("Tripstops");
                });
#pragma warning restore 612, 618
        }
    }
}
