// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelOrganiserTool.Data;

#nullable disable

namespace TravelOrganiserTool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240130063420_initialCreate9")]
    partial class initialCreate9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionID");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Australia",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "China",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "India",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Japan",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Malaysia",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Philippines",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Singapore",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "South Korea",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Thailand",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Vietnam",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Belgium",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "Denmark",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "Finland",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 14,
                            Name = "France",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 15,
                            Name = "Germany",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "Ireland",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 17,
                            Name = "Italy",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "Norway",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "United Kingdom",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bahamas",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 21,
                            Name = "Canada",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 22,
                            Name = "Jamaica",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 23,
                            Name = "Mexico",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 24,
                            Name = "United States",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 25,
                            Name = "Argentina",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 26,
                            Name = "Brazil",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 27,
                            Name = "Chile",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 28,
                            Name = "Ecuador",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 29,
                            Name = "Peru",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 30,
                            Name = "Ethiopia",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 31,
                            Name = "Kenya",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 32,
                            Name = "Nigeria",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 33,
                            Name = "Rwanda",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 34,
                            Name = "South Africa",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 35,
                            Name = "Zimbabwe",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 36,
                            Name = "Antarctica",
                            RegionID = 7
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryID");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryID = 1,
                            Name = "Adelaide"
                        },
                        new
                        {
                            Id = 2,
                            CountryID = 1,
                            Name = "Brisbane"
                        },
                        new
                        {
                            Id = 3,
                            CountryID = 1,
                            Name = "Canberra"
                        },
                        new
                        {
                            Id = 4,
                            CountryID = 1,
                            Name = "Hobart"
                        },
                        new
                        {
                            Id = 5,
                            CountryID = 1,
                            Name = "Melbourne"
                        },
                        new
                        {
                            Id = 6,
                            CountryID = 1,
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = 7,
                            CountryID = 1,
                            Name = "Perth"
                        },
                        new
                        {
                            Id = 8,
                            CountryID = 2,
                            Name = "Beijing"
                        },
                        new
                        {
                            Id = 9,
                            CountryID = 2,
                            Name = "Shanghai"
                        },
                        new
                        {
                            Id = 10,
                            CountryID = 3,
                            Name = "Mumbai"
                        },
                        new
                        {
                            Id = 11,
                            CountryID = 3,
                            Name = "Kolkata"
                        },
                        new
                        {
                            Id = 12,
                            CountryID = 3,
                            Name = "Hyderabad"
                        },
                        new
                        {
                            Id = 13,
                            CountryID = 4,
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = 14,
                            CountryID = 4,
                            Name = "Osaka"
                        },
                        new
                        {
                            Id = 15,
                            CountryID = 4,
                            Name = "Hiroshima"
                        },
                        new
                        {
                            Id = 16,
                            CountryID = 5,
                            Name = "Kuala Lumpur"
                        },
                        new
                        {
                            Id = 17,
                            CountryID = 6,
                            Name = "Manila"
                        },
                        new
                        {
                            Id = 18,
                            CountryID = 7,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 19,
                            CountryID = 8,
                            Name = "Seoul"
                        },
                        new
                        {
                            Id = 20,
                            CountryID = 9,
                            Name = "Bangkok"
                        },
                        new
                        {
                            Id = 21,
                            CountryID = 9,
                            Name = "Phuket"
                        },
                        new
                        {
                            Id = 22,
                            CountryID = 10,
                            Name = "Ho Chi Minh City"
                        },
                        new
                        {
                            Id = 23,
                            CountryID = 10,
                            Name = "Hanoi"
                        },
                        new
                        {
                            Id = 24,
                            CountryID = 11,
                            Name = "Brussels"
                        },
                        new
                        {
                            Id = 25,
                            CountryID = 11,
                            Name = "Bruges"
                        },
                        new
                        {
                            Id = 26,
                            CountryID = 12,
                            Name = "Copenhagen"
                        },
                        new
                        {
                            Id = 27,
                            CountryID = 13,
                            Name = "Helsinki"
                        },
                        new
                        {
                            Id = 28,
                            CountryID = 14,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 29,
                            CountryID = 15,
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 30,
                            CountryID = 16,
                            Name = "Dublin"
                        },
                        new
                        {
                            Id = 31,
                            CountryID = 16,
                            Name = "Galway"
                        },
                        new
                        {
                            Id = 32,
                            CountryID = 17,
                            Name = "Rome"
                        },
                        new
                        {
                            Id = 33,
                            CountryID = 17,
                            Name = "Venice"
                        },
                        new
                        {
                            Id = 34,
                            CountryID = 17,
                            Name = "Florence"
                        },
                        new
                        {
                            Id = 35,
                            CountryID = 18,
                            Name = "Oslo"
                        },
                        new
                        {
                            Id = 36,
                            CountryID = 19,
                            Name = "London"
                        },
                        new
                        {
                            Id = 37,
                            CountryID = 19,
                            Name = "Bristol"
                        },
                        new
                        {
                            Id = 38,
                            CountryID = 19,
                            Name = "Manchester"
                        },
                        new
                        {
                            Id = 39,
                            CountryID = 19,
                            Name = "Birmingham"
                        },
                        new
                        {
                            Id = 40,
                            CountryID = 6,
                            Name = "New York"
                        },
                        new
                        {
                            Id = 41,
                            CountryID = 7,
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = 42,
                            CountryID = 8,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 43,
                            CountryID = 9,
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = 44,
                            CountryID = 10,
                            Name = "Johannesburg"
                        },
                        new
                        {
                            Id = 45,
                            CountryID = 11,
                            Name = "Nairobi"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Region");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Asia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Europe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "North America"
                        },
                        new
                        {
                            Id = 5,
                            Name = "South America"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Africa"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Antarctica"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationID");

                    b.ToTable("Trip");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocationID = 1,
                            Name = "Example Trip: Visiting Family in Sydney"
                        },
                        new
                        {
                            Id = 2,
                            LocationID = 2,
                            Name = "Example Trip: Visiting Tokyo"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.Region", "Region")
                        .WithMany("Countries")
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Location", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.Country", "Country")
                        .WithMany("Locations")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Trip", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.Location", "Location")
                        .WithMany("Trips")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Location", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Region", b =>
                {
                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
