// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelOrganiserTool.Data;

#nullable disable

namespace TravelOrganiserTool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelOrganiserTool.Models.ClimateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClimateType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sunny"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tropical"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chilly"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Snowy"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageFilename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionID");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageFilename = "australia.jpg",
                            Name = "Australia",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageFilename = "no-image.jpg",
                            Name = "Cook Islands",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageFilename = "no-image.jpg",
                            Name = "Fiji",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageFilename = "no-image.jpg",
                            Name = "Kiribati",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageFilename = "no-image.jpg",
                            Name = "Marshall Islands",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 6,
                            ImageFilename = "no-image.jpg",
                            Name = "Micronesia",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 7,
                            ImageFilename = "no-image.jpg",
                            Name = "Nauru",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 8,
                            ImageFilename = "no-image.jpg",
                            Name = "New Zealand",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 9,
                            ImageFilename = "no-image.jpg",
                            Name = "Papua New Guinea",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 10,
                            ImageFilename = "no-image.jpg",
                            Name = "Samoa",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 11,
                            ImageFilename = "no-image.jpg",
                            Name = "Solomon Islands",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 12,
                            ImageFilename = "no-image.jpg",
                            Name = "Tonga",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 13,
                            ImageFilename = "no-image.jpg",
                            Name = "Vanuatu",
                            RegionID = 1
                        },
                        new
                        {
                            Id = 14,
                            ImageFilename = "no-image.jpg",
                            Name = "Brunei",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 15,
                            ImageFilename = "no-image.jpg",
                            Name = "Burma",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 16,
                            ImageFilename = "no-image.jpg",
                            Name = "Cambodia",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 17,
                            ImageFilename = "no-image.jpg",
                            Name = "Timor-Leste",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 18,
                            ImageFilename = "no-image.jpg",
                            Name = "Indonesia",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 19,
                            ImageFilename = "no-image.jpg",
                            Name = "Laos",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 20,
                            ImageFilename = "malaysia.jpg",
                            Name = "Malaysia",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 21,
                            ImageFilename = "no-image.jpg",
                            Name = "Myanmar",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 22,
                            ImageFilename = "philippines.jpg",
                            Name = "Philippines",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 23,
                            ImageFilename = "singapore.jpg",
                            Name = "Singapore",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 24,
                            ImageFilename = "thailand.jpg",
                            Name = "Thailand",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 25,
                            ImageFilename = "vietnam.jpg",
                            Name = "Vietnam",
                            RegionID = 2
                        },
                        new
                        {
                            Id = 26,
                            ImageFilename = "china.jpg",
                            Name = "China",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 27,
                            ImageFilename = "japan.jpg",
                            Name = "Japan",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 28,
                            ImageFilename = "no-image.jpg",
                            Name = "Mongolia",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 29,
                            ImageFilename = "south-korea.jpg",
                            Name = "South Korea",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 30,
                            ImageFilename = "no-image.jpg",
                            Name = "North Korea",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 31,
                            ImageFilename = "no-image.jpg",
                            Name = "Taiwan",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 32,
                            ImageFilename = "no-image.jpg",
                            Name = "Macao",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 33,
                            ImageFilename = "no-image.jpg",
                            Name = "Hong Kong",
                            RegionID = 3
                        },
                        new
                        {
                            Id = 34,
                            ImageFilename = "no-image.jpg",
                            Name = "Afghanistan",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 35,
                            ImageFilename = "no-image.jpg",
                            Name = "Bangladesh",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 36,
                            ImageFilename = "no-image.jpg",
                            Name = "Bhutan",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 37,
                            ImageFilename = "india.jpg",
                            Name = "India",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 38,
                            ImageFilename = "no-image.jpg",
                            Name = "Nepal",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 39,
                            ImageFilename = "no-image.jpg",
                            Name = "Maldives",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 40,
                            ImageFilename = "no-image.jpg",
                            Name = "Pakistan",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 41,
                            ImageFilename = "no-image.jpg",
                            Name = "Sri Lanka",
                            RegionID = 4
                        },
                        new
                        {
                            Id = 42,
                            ImageFilename = "no-image.jpg",
                            Name = "Bahrain",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 43,
                            ImageFilename = "no-image.jpg",
                            Name = "Iran",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 44,
                            ImageFilename = "no-image.jpg",
                            Name = "Iraq",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 45,
                            ImageFilename = "no-image.jpg",
                            Name = "Israel",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 46,
                            ImageFilename = "no-image.jpg",
                            Name = "Jordan",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 47,
                            ImageFilename = "no-image.jpg",
                            Name = "Kuwait",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 48,
                            ImageFilename = "no-image.jpg",
                            Name = "Lebanon",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 49,
                            ImageFilename = "no-image.jpg",
                            Name = "Oman",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 50,
                            ImageFilename = "no-image.jpg",
                            Name = "Palestine",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 51,
                            ImageFilename = "no-image.jpg",
                            Name = "Qatar",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 52,
                            ImageFilename = "no-image.jpg",
                            Name = "Saudi Arabia",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 53,
                            ImageFilename = "no-image.jpg",
                            Name = "Syria",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 54,
                            ImageFilename = "no-image.jpg",
                            Name = "United Arab Emirates",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 55,
                            ImageFilename = "no-image.jpg",
                            Name = "Yemen",
                            RegionID = 5
                        },
                        new
                        {
                            Id = 56,
                            ImageFilename = "denmark.jpg",
                            Name = "Denmark",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 57,
                            ImageFilename = "norway.jpg",
                            Name = "Norway",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 58,
                            ImageFilename = "no-image.jpg",
                            Name = "Sweden",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 59,
                            ImageFilename = "no-image.jpg",
                            Name = "Faroe Islands",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 60,
                            ImageFilename = "finland.jpg",
                            Name = "Finland",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 61,
                            ImageFilename = "no-image.jpg",
                            Name = "Iceland",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 62,
                            ImageFilename = "no-image.jpg",
                            Name = "Greenland",
                            RegionID = 6
                        },
                        new
                        {
                            Id = 63,
                            ImageFilename = "england.jpg",
                            Name = "England",
                            RegionID = 7
                        },
                        new
                        {
                            Id = 64,
                            ImageFilename = "no-image.jpg",
                            Name = "Scotland",
                            RegionID = 7
                        },
                        new
                        {
                            Id = 65,
                            ImageFilename = "no-image.jpg",
                            Name = "Wales",
                            RegionID = 7
                        },
                        new
                        {
                            Id = 66,
                            ImageFilename = "no-image.jpg",
                            Name = "North Ireland",
                            RegionID = 7
                        },
                        new
                        {
                            Id = 67,
                            ImageFilename = "ireland.jpg",
                            Name = "Republic of Ireland",
                            RegionID = 7
                        },
                        new
                        {
                            Id = 68,
                            ImageFilename = "no-image.jpg",
                            Name = "Austria",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 69,
                            ImageFilename = "no-image.jpg",
                            Name = "Bulgaria",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 70,
                            ImageFilename = "no-image.jpg",
                            Name = "Belgium",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 71,
                            ImageFilename = "no-image.jpg",
                            Name = "Czech Republic",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 72,
                            ImageFilename = "france.jpg",
                            Name = "France",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 73,
                            ImageFilename = "germany.jpg",
                            Name = "Germany",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 74,
                            ImageFilename = "no-image.jpg",
                            Name = "Hungary",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 75,
                            ImageFilename = "no-image.jpg",
                            Name = "Liechtenstein",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 76,
                            ImageFilename = "no-image.jpg",
                            Name = "Lithuania",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 77,
                            ImageFilename = "no-image.jpg",
                            Name = "Luxembourg",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 78,
                            ImageFilename = "no-image.jpg",
                            Name = "Netherlands",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 79,
                            ImageFilename = "no-image.jpg",
                            Name = "Poland",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 80,
                            ImageFilename = "no-image.jpg",
                            Name = "Romania",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 81,
                            ImageFilename = "no-image.jpg",
                            Name = "Serbia",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 82,
                            ImageFilename = "no-image.jpg",
                            Name = "Slovakia",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 83,
                            ImageFilename = "no-image.jpg",
                            Name = "Switzerland",
                            RegionID = 8
                        },
                        new
                        {
                            Id = 84,
                            ImageFilename = "no-image.jpg",
                            Name = "Albania",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 85,
                            ImageFilename = "no-image.jpg",
                            Name = "Andorra",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 86,
                            ImageFilename = "no-image.jpg",
                            Name = "Bosnia",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 87,
                            ImageFilename = "no-image.jpg",
                            Name = "Croatia",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 88,
                            ImageFilename = "no-image.jpg",
                            Name = "Cyprus",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 89,
                            ImageFilename = "no-image.jpg",
                            Name = "Greece",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 90,
                            ImageFilename = "italy.jpg",
                            Name = "Italy",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 91,
                            ImageFilename = "no-image.jpg",
                            Name = "Kosovo",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 92,
                            ImageFilename = "no-image.jpg",
                            Name = "Malta",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 93,
                            ImageFilename = "no-image.jpg",
                            Name = "Monaco",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 94,
                            ImageFilename = "no-image.jpg",
                            Name = "Montenegro",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 95,
                            ImageFilename = "no-image.jpg",
                            Name = "North Macedonia",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 96,
                            ImageFilename = "no-image.jpg",
                            Name = "Portugal",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 97,
                            ImageFilename = "no-image.jpg",
                            Name = "Slovenia",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 98,
                            ImageFilename = "no-image.jpg",
                            Name = "Spain",
                            RegionID = 9
                        },
                        new
                        {
                            Id = 99,
                            ImageFilename = "no-image.jpg",
                            Name = "Armenia",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 100,
                            ImageFilename = "no-image.jpg",
                            Name = "Azerbaijan",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 101,
                            ImageFilename = "no-image.jpg",
                            Name = "Belarus",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 102,
                            ImageFilename = "no-image.jpg",
                            Name = "Estonia",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 103,
                            ImageFilename = "no-image.jpg",
                            Name = "Georgia",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 104,
                            ImageFilename = "no-image.jpg",
                            Name = "Kazakhstan",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 105,
                            ImageFilename = "no-image.jpg",
                            Name = "Kyrgyzstan",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 106,
                            ImageFilename = "no-image.jpg",
                            Name = "Latvia",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 107,
                            ImageFilename = "no-image.jpg",
                            Name = "Lithuania",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 108,
                            ImageFilename = "no-image.jpg",
                            Name = "Moldova",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 109,
                            ImageFilename = "no-image.jpg",
                            Name = "Russia",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 110,
                            ImageFilename = "no-image.jpg",
                            Name = "Tajikistan",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 111,
                            ImageFilename = "no-image.jpg",
                            Name = "Turkmenistan",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 112,
                            ImageFilename = "no-image.jpg",
                            Name = "Ukraine",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 113,
                            ImageFilename = "no-image.jpg",
                            Name = "Uzbekistan",
                            RegionID = 17
                        },
                        new
                        {
                            Id = 114,
                            ImageFilename = "no-image.jpg",
                            Name = "Algeria",
                            RegionID = 10
                        },
                        new
                        {
                            Id = 115,
                            ImageFilename = "no-image.jpg",
                            Name = "Egypt",
                            RegionID = 10
                        },
                        new
                        {
                            Id = 116,
                            ImageFilename = "no-image.jpg",
                            Name = "Libya",
                            RegionID = 10
                        },
                        new
                        {
                            Id = 117,
                            ImageFilename = "no-image.jpg",
                            Name = "Morocco",
                            RegionID = 10
                        },
                        new
                        {
                            Id = 118,
                            ImageFilename = "no-image.jpg",
                            Name = "Sudan",
                            RegionID = 10
                        },
                        new
                        {
                            Id = 119,
                            ImageFilename = "no-image.jpg",
                            Name = "Tunisia",
                            RegionID = 10
                        },
                        new
                        {
                            Id = 120,
                            ImageFilename = "no-image.jpg",
                            Name = "Angola",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 121,
                            ImageFilename = "no-image.jpg",
                            Name = "Benin",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 122,
                            ImageFilename = "no-image.jpg",
                            Name = "Botswana",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 123,
                            ImageFilename = "no-image.jpg",
                            Name = "Burkina Faso",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 124,
                            ImageFilename = "no-image.jpg",
                            Name = "Burundi",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 125,
                            ImageFilename = "no-image.jpg",
                            Name = "Cameroon",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 126,
                            ImageFilename = "no-image.jpg",
                            Name = "Cape Verde",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 127,
                            ImageFilename = "no-image.jpg",
                            Name = "Central African Republic",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 128,
                            ImageFilename = "no-image.jpg",
                            Name = "Chad",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 129,
                            ImageFilename = "no-image.jpg",
                            Name = "Comoros",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 130,
                            ImageFilename = "no-image.jpg",
                            Name = "Democratic Republic of the Congo",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 131,
                            ImageFilename = "no-image.jpg",
                            Name = "Djibouti",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 132,
                            ImageFilename = "no-image.jpg",
                            Name = "Equatorial Guinea",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 133,
                            ImageFilename = "no-image.jpg",
                            Name = "Eritrea",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 134,
                            ImageFilename = "no-image.jpg",
                            Name = "Eswatini",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 135,
                            ImageFilename = "ethiopia.jpg",
                            Name = "Ethiopia",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 136,
                            ImageFilename = "no-image.jpg",
                            Name = "Gabon",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 137,
                            ImageFilename = "no-image.jpg",
                            Name = "Gambia",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 138,
                            ImageFilename = "no-image.jpg",
                            Name = "Ghana",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 139,
                            ImageFilename = "no-image.jpg",
                            Name = "Guinea",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 140,
                            ImageFilename = "no-image.jpg",
                            Name = "Guinea - Bissau",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 141,
                            ImageFilename = "no-image.jpg",
                            Name = "Ivory Coast",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 142,
                            ImageFilename = "kenya.jpg",
                            Name = "Kenya",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 143,
                            ImageFilename = "no-image.jpg",
                            Name = "Lesotho",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 144,
                            ImageFilename = "no-image.jpg",
                            Name = "Liberia",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 145,
                            ImageFilename = "no-image.jpg",
                            Name = "Madagascar",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 146,
                            ImageFilename = "no-image.jpg",
                            Name = "Malawi",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 147,
                            ImageFilename = "no-image.jpg",
                            Name = "Mali",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 148,
                            ImageFilename = "no-image.jpg",
                            Name = "Mauritania",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 149,
                            ImageFilename = "no-image.jpg",
                            Name = "Mauritius",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 150,
                            ImageFilename = "no-image.jpg",
                            Name = "Mozambique",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 151,
                            ImageFilename = "no-image.jpg",
                            Name = "Namibia",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 152,
                            ImageFilename = "no-image.jpg",
                            Name = "Niger",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 153,
                            ImageFilename = "nigeria.jpg",
                            Name = "Nigeria",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 154,
                            ImageFilename = "rwanda.jpg",
                            Name = "Rwanda",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 155,
                            ImageFilename = "no-image.jpg",
                            Name = "Sao Tome and Príncipe",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 156,
                            ImageFilename = "no-image.jpg",
                            Name = "Senegal",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 157,
                            ImageFilename = "no-image.jpg",
                            Name = "Seychelles",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 158,
                            ImageFilename = "no-image.jpg",
                            Name = "Sierra Leone",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 159,
                            ImageFilename = "no-image.jpg",
                            Name = "Somalia",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 160,
                            ImageFilename = "south-africa.jpg",
                            Name = "South Africa",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 161,
                            ImageFilename = "no-image.jpg",
                            Name = "South Sudan",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 162,
                            ImageFilename = "no-image.jpg",
                            Name = "Sudan",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 163,
                            ImageFilename = "no-image.jpg",
                            Name = "Tanzania",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 164,
                            ImageFilename = "no-image.jpg",
                            Name = "Togo",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 165,
                            ImageFilename = "no-image.jpg",
                            Name = "Uganda",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 166,
                            ImageFilename = "no-image.jpg",
                            Name = "Zambia",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 167,
                            ImageFilename = "zimbabwe.jpg",
                            Name = "Zimbabwe",
                            RegionID = 11
                        },
                        new
                        {
                            Id = 168,
                            ImageFilename = "canada.jpg",
                            Name = "Canada",
                            RegionID = 12
                        },
                        new
                        {
                            Id = 169,
                            ImageFilename = "mexico.jpg",
                            Name = "Mexico",
                            RegionID = 12
                        },
                        new
                        {
                            Id = 170,
                            ImageFilename = "united-states.jpg",
                            Name = "United States",
                            RegionID = 12
                        },
                        new
                        {
                            Id = 171,
                            ImageFilename = "no-image.jpg",
                            Name = "Belize",
                            RegionID = 13
                        },
                        new
                        {
                            Id = 172,
                            ImageFilename = "no-image.jpg",
                            Name = "Costa Rica",
                            RegionID = 13
                        },
                        new
                        {
                            Id = 173,
                            ImageFilename = "no-image.jpg",
                            Name = "El Salvador",
                            RegionID = 13
                        },
                        new
                        {
                            Id = 174,
                            ImageFilename = "no-image.jpg",
                            Name = "Guatemala",
                            RegionID = 13
                        },
                        new
                        {
                            Id = 175,
                            ImageFilename = "no-image.jpg",
                            Name = "Honduras",
                            RegionID = 13
                        },
                        new
                        {
                            Id = 176,
                            ImageFilename = "no-image.jpg",
                            Name = "Nicaragua",
                            RegionID = 13
                        },
                        new
                        {
                            Id = 177,
                            ImageFilename = "no-image.jpg",
                            Name = "Panama",
                            RegionID = 13
                        },
                        new
                        {
                            Id = 178,
                            ImageFilename = "no-image.jpg",
                            Name = "Aruba",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 179,
                            ImageFilename = "no-image.jpg",
                            Name = "Anguilla",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 180,
                            ImageFilename = "no-image.jpg",
                            Name = "Antigua and Barbuda",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 181,
                            ImageFilename = "no-image.jpg",
                            Name = "Bahamas",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 182,
                            ImageFilename = "no-image.jpg",
                            Name = "Barbados",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 183,
                            ImageFilename = "no-image.jpg",
                            Name = "Bermuda",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 184,
                            ImageFilename = "no-image.jpg",
                            Name = "Cuba",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 185,
                            ImageFilename = "no-image.jpg",
                            Name = "Dominica",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 186,
                            ImageFilename = "no-image.jpg",
                            Name = "Dominican Republic",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 187,
                            ImageFilename = "no-image.jpg",
                            Name = "Haiti",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 188,
                            ImageFilename = "jamaica.jpg",
                            Name = "Jamaica",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 189,
                            ImageFilename = "no-image.jpg",
                            Name = "Puerto Rico",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 190,
                            ImageFilename = "no-image.jpg",
                            Name = "St. Kitts and Nevis",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 191,
                            ImageFilename = "no-image.jpg",
                            Name = "St. Lucia",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 192,
                            ImageFilename = "no-image.jpg",
                            Name = "St. Vincent and the Grenadines",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 193,
                            ImageFilename = "no-image.jpg",
                            Name = "Grenada",
                            RegionID = 14
                        },
                        new
                        {
                            Id = 194,
                            ImageFilename = "no-image.jpg",
                            Name = "Argentina",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 195,
                            ImageFilename = "no-image.jpg",
                            Name = "Bolivia",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 196,
                            ImageFilename = "brazil.jpg",
                            Name = "Brazil",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 197,
                            ImageFilename = "chile.jpg",
                            Name = "Chile",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 198,
                            ImageFilename = "no-image.jpg",
                            Name = "Colombia",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 199,
                            ImageFilename = "ecuador.jpg",
                            Name = "Ecuador",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 200,
                            ImageFilename = "no-image.jpg",
                            Name = "Guyana",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 201,
                            ImageFilename = "no-image.jpg",
                            Name = "Paraguay",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 202,
                            ImageFilename = "peru.jpg",
                            Name = "Peru",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 203,
                            ImageFilename = "no-image.jpg",
                            Name = "Suriname",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 204,
                            ImageFilename = "no-image.jpg",
                            Name = "Uruguay",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 205,
                            ImageFilename = "no-image.jpg",
                            Name = "Venezuela",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 206,
                            ImageFilename = "no-image.jpg",
                            Name = "Trinidad and Tobago",
                            RegionID = 15
                        },
                        new
                        {
                            Id = 207,
                            ImageFilename = "no-image.jpg",
                            Name = "Antarctica",
                            RegionID = 16
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClimateTypeID")
                        .HasColumnType("int");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("ImageFilename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PopulationTypeID")
                        .HasColumnType("int");

                    b.Property<int>("TerrainTypeID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClimateTypeID");

                    b.HasIndex("CountryID");

                    b.HasIndex("PopulationTypeID");

                    b.HasIndex("TerrainTypeID");

                    b.ToTable("Destination");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "adelaide.jpg",
                            Name = "Adelaide",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 2,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "brisbane.jpg",
                            Name = "Brisbane",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 3,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "canberra.jpg",
                            Name = "Canberra",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 4,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "hobart.jpg",
                            Name = "Hobart",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 5,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "melbourne.jpg",
                            Name = "Melbourne",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 6,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "sydney.jpg",
                            Name = "Sydney",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 7,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "perth.jpg",
                            Name = "Perth",
                            PopulationTypeID = 1,
                            TerrainTypeID = 1
                        },
                        new
                        {
                            Id = 8,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "no-image.jpg",
                            Name = "Newcastle",
                            PopulationTypeID = 1,
                            TerrainTypeID = 9
                        },
                        new
                        {
                            Id = 9,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "no-image.jpg",
                            Name = "Central Coast",
                            PopulationTypeID = 2,
                            TerrainTypeID = 9
                        },
                        new
                        {
                            Id = 10,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "no-image.jpg",
                            Name = "Hunter Valley",
                            PopulationTypeID = 2,
                            TerrainTypeID = 7
                        },
                        new
                        {
                            Id = 11,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "no-image.jpg",
                            Name = "Nelson Bay",
                            PopulationTypeID = 2,
                            TerrainTypeID = 9
                        },
                        new
                        {
                            Id = 12,
                            ClimateTypeID = 1,
                            CountryID = 1,
                            ImageFilename = "no-image.jpg",
                            Name = "Port Macquarie",
                            PopulationTypeID = 2,
                            TerrainTypeID = 9
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.PopulationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PopulationType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "City"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Town"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rural (Non Urban)"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Region");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oceania"
                        },
                        new
                        {
                            Id = 2,
                            Name = "South East Asia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "East Asia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "South Asia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Middle East"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Scandinavia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "United Kingdom and Western Europe"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Central Europe"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Southern Europe"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Eastern Europe and Former USSR"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Northern Africa"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Subsaharan Africa"
                        },
                        new
                        {
                            Id = 12,
                            Name = "North America"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Central America"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Caribbean"
                        },
                        new
                        {
                            Id = 15,
                            Name = "South America"
                        },
                        new
                        {
                            Id = 16,
                            Name = "South Pole"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.TerrainType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TerrainType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Major Cities"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Desert"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Forest"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cliffs"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hills"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Marsh"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Farmland"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Beach"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Coastal"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Waterfront"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Mountains"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trip");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Example Trip: Visiting Family in Sydney"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Example Trip: Visiting Tokyo"
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Tripstop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Enddate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Startdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationID");

                    b.HasIndex("TripID");

                    b.ToTable("Tripstop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DestinationID = 1,
                            Enddate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Startdate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            TripID = 1
                        },
                        new
                        {
                            Id = 2,
                            DestinationID = 2,
                            Enddate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Startdate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            TripID = 1
                        },
                        new
                        {
                            Id = 3,
                            DestinationID = 3,
                            Enddate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Startdate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            TripID = 2
                        },
                        new
                        {
                            Id = 4,
                            DestinationID = 4,
                            Enddate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Startdate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            TripID = 2
                        });
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.Region", "Region")
                        .WithMany("Countries")
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Destination", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.ClimateType", "ClimateType")
                        .WithMany("Destinations")
                        .HasForeignKey("ClimateTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelOrganiserTool.Models.Country", "Country")
                        .WithMany("Destinations")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelOrganiserTool.Models.PopulationType", "PopulationType")
                        .WithMany("Destinations")
                        .HasForeignKey("PopulationTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelOrganiserTool.Models.TerrainType", "TerrainType")
                        .WithMany("Destinations")
                        .HasForeignKey("TerrainTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClimateType");

                    b.Navigation("Country");

                    b.Navigation("PopulationType");

                    b.Navigation("TerrainType");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Tripstop", b =>
                {
                    b.HasOne("TravelOrganiserTool.Models.Destination", "Destination")
                        .WithMany("Tripstops")
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelOrganiserTool.Models.Trip", "Trip")
                        .WithMany("Tripstops")
                        .HasForeignKey("TripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.ClimateType", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Country", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Destination", b =>
                {
                    b.Navigation("Tripstops");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.PopulationType", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Region", b =>
                {
                    b.Navigation("Countries");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.TerrainType", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("TravelOrganiserTool.Models.Trip", b =>
                {
                    b.Navigation("Tripstops");
                });
#pragma warning restore 612, 618
        }
    }
}
